---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: usuarios y publicaciones
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: usuarios y likes
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: usuarios y usuarios
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: usuarios y comentarios
  checked: false
name: Siempre yo te sigo a todas partes
